package hibernate;

// Generated 26-giu-2014 10.57.23 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Argomenti generated by hbm2java
 */
@Entity
@Table(name = "argomenti", catalog = "supermercati")
public class Argomenti implements java.io.Serializable {

	private String argomento;
	private Set argomentiInserziones = new HashSet(0);

	public Argomenti() {
	}

	public Argomenti(String argomento) {
		this.argomento = argomento;
	}

	public Argomenti(String argomento, Set argomentiInserziones) {
		this.argomento = argomento;
		this.argomentiInserziones = argomentiInserziones;
	}

	@Id
	@Column(name = "Argomento", unique = true, nullable = false, length = 30)
	public String getArgomento() {
		return this.argomento;
	}

	public void setArgomento(String argomento) {
		this.argomento = argomento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "argomenti")
	public Set getArgomentiInserziones() {
		return this.argomentiInserziones;
	}

	public void setArgomentiInserziones(Set argomentiInserziones) {
		this.argomentiInserziones = argomentiInserziones;
	}

}
