package hibernate;

// Generated 28-apr-2014 22.53.51 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ListaSpesaProdottiId generated by hbm2java
 */
@Embeddable
public class ListaSpesaProdottiId implements java.io.Serializable {

	private int idElemento;
	private int idListaSpesa;

	public ListaSpesaProdottiId() {
	}

	public ListaSpesaProdottiId(int idElemento, int idListaSpesa) {
		this.idElemento = idElemento;
		this.idListaSpesa = idListaSpesa;
	}

	@Column(name = "ID_Elemento", nullable = false)
	public int getIdElemento() {
		return this.idElemento;
	}

	public void setIdElemento(int idElemento) {
		this.idElemento = idElemento;
	}

	@Column(name = "ID_ListaSpesa", nullable = false)
	public int getIdListaSpesa() {
		return this.idListaSpesa;
	}

	public void setIdListaSpesa(int idListaSpesa) {
		this.idListaSpesa = idListaSpesa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ListaSpesaProdottiId))
			return false;
		ListaSpesaProdottiId castOther = (ListaSpesaProdottiId) other;

		return (this.getIdElemento() == castOther.getIdElemento())
				&& (this.getIdListaSpesa() == castOther.getIdListaSpesa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdElemento();
		result = 37 * result + this.getIdListaSpesa();
		return result;
	}

}
