package hibernate;

// Generated 2-giu-2014 22.11.49 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ListaSpesa generated by hbm2java
 */
@Entity
@Table(name = "lista_spesa", catalog = "supermercati")
public class ListaSpesa implements java.io.Serializable {

	private int idSpesa;
	private Utente utente;
	private String nomeListaSpesa;
	private Set listaSpesaProdottis = new HashSet(0);

	public ListaSpesa() {
	}

	public ListaSpesa(int idSpesa, Utente utente, String nomeListaSpesa) {
		this.idSpesa = idSpesa;
		this.utente = utente;
		this.nomeListaSpesa = nomeListaSpesa;
	}

	public ListaSpesa(int idSpesa, Utente utente, String nomeListaSpesa,
			Set listaSpesaProdottis) {
		this.idSpesa = idSpesa;
		this.utente = utente;
		this.nomeListaSpesa = nomeListaSpesa;
		this.listaSpesaProdottis = listaSpesaProdottis;
	}

	@Id
	@Column(name = "ID_Spesa", unique = true, nullable = false)
	public int getIdSpesa() {
		return this.idSpesa;
	}

	public void setIdSpesa(int idSpesa) {
		this.idSpesa = idSpesa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_Utente", nullable = false)
	public Utente getUtente() {
		return this.utente;
	}

	public void setUtente(Utente utente) {
		this.utente = utente;
	}

	@Column(name = "NomeListaSpesa", nullable = false, length = 45)
	public String getNomeListaSpesa() {
		return this.nomeListaSpesa;
	}

	public void setNomeListaSpesa(String nomeListaSpesa) {
		this.nomeListaSpesa = nomeListaSpesa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "listaSpesa")
	public Set getListaSpesaProdottis() {
		return this.listaSpesaProdottis;
	}

	public void setListaSpesaProdottis(Set listaSpesaProdottis) {
		this.listaSpesaProdottis = listaSpesaProdottis;
	}

}
