package hibernate;

// Generated 2-mag-2014 16.20.34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ListaSpesaProdotti generated by hbm2java
 */
@Entity
@Table(name = "lista_spesa_prodotti", catalog = "supermercati")
public class ListaSpesaProdotti implements java.io.Serializable {

	private ListaSpesaProdottiId id;
	private ListaSpesa listaSpesa;
	private String descrizione;
	private Date dataAcquisto;
	private Integer quantità;

	public ListaSpesaProdotti() {
	}

	public ListaSpesaProdotti(ListaSpesaProdottiId id, ListaSpesa listaSpesa,
			String descrizione, Date dataAcquisto) {
		this.id = id;
		this.listaSpesa = listaSpesa;
		this.descrizione = descrizione;
		this.dataAcquisto = dataAcquisto;
	}

	public ListaSpesaProdotti(ListaSpesaProdottiId id, ListaSpesa listaSpesa,
			String descrizione, Date dataAcquisto, Integer quantità) {
		this.id = id;
		this.listaSpesa = listaSpesa;
		this.descrizione = descrizione;
		this.dataAcquisto = dataAcquisto;
		this.quantità = quantità;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idElemento", column = @Column(name = "ID_Elemento", nullable = false)),
			@AttributeOverride(name = "idListaSpesa", column = @Column(name = "ID_ListaSpesa", nullable = false)) })
	public ListaSpesaProdottiId getId() {
		return this.id;
	}

	public void setId(ListaSpesaProdottiId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ListaSpesa", nullable = false, insertable = false, updatable = false)
	public ListaSpesa getListaSpesa() {
		return this.listaSpesa;
	}

	public void setListaSpesa(ListaSpesa listaSpesa) {
		this.listaSpesa = listaSpesa;
	}

	@Column(name = "Descrizione", nullable = false, length = 45)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DataAcquisto", nullable = false, length = 10)
	public Date getDataAcquisto() {
		return this.dataAcquisto;
	}

	public void setDataAcquisto(Date dataAcquisto) {
		this.dataAcquisto = dataAcquisto;
	}

	@Column(name = "Quantità")
	public Integer getQuantità() {
		return this.quantità;
	}

	public void setQuantità(Integer quantità) {
		this.quantità = quantità;
	}

}
