package hibernate;

// Generated 2-mag-2014 16.20.34 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ListaDesideriProdotti generated by hbm2java
 */
@Entity
@Table(name = "lista_desideri_prodotti", catalog = "supermercati")
public class ListaDesideriProdotti implements java.io.Serializable {

	private ListaDesideriProdottiId id;
	private ListaDesideri listaDesideri;
	private String descrizione;
	private Integer quantità;

	public ListaDesideriProdotti() {
	}

	public ListaDesideriProdotti(ListaDesideriProdottiId id,
			ListaDesideri listaDesideri, String descrizione) {
		this.id = id;
		this.listaDesideri = listaDesideri;
		this.descrizione = descrizione;
	}

	public ListaDesideriProdotti(ListaDesideriProdottiId id,
			ListaDesideri listaDesideri, String descrizione, Integer quantità) {
		this.id = id;
		this.listaDesideri = listaDesideri;
		this.descrizione = descrizione;
		this.quantità = quantità;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idElemento", column = @Column(name = "ID_Elemento", nullable = false)),
			@AttributeOverride(name = "idListaDesideri", column = @Column(name = "ID_ListaDesideri", nullable = false)) })
	public ListaDesideriProdottiId getId() {
		return this.id;
	}

	public void setId(ListaDesideriProdottiId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ListaDesideri", nullable = false, insertable = false, updatable = false)
	public ListaDesideri getListaDesideri() {
		return this.listaDesideri;
	}

	public void setListaDesideri(ListaDesideri listaDesideri) {
		this.listaDesideri = listaDesideri;
	}

	@Column(name = "Descrizione", nullable = false, length = 45)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Column(name = "Quantità")
	public Integer getQuantità() {
		return this.quantità;
	}

	public void setQuantità(Integer quantità) {
		this.quantità = quantità;
	}

}
